import { Router } from "express";
import ordersController from "@controllers/orders";
const ordersRouter = Router();
ordersRouter.post("/",ordersController.create);
ordersRouter.post("/order",ordersController.order);
ordersRouter.get("/", ordersController.read);
ordersRouter.get("/:id", ordersController.readOne);
ordersRouter.put("/:id",ordersController.update);
ordersRouter.delete("/:id",ordersController.delete);
ordersRouter.get("/:id/user",ordersController.userOrder);
export default ordersRouter;